# Generated by Django 4.2.6 on 2023-10-11 17:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('logo', models.ImageField(upload_to='jobs/company_logos')),
                ('type', models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], max_length=50)),
                ('loctaion', models.TextField(max_length=200)),
                ('experience', models.CharField(choices=[('1-2', '1-2'), ('2-3', '2-3'), ('3-6', '3-6'), ('6+', '6+')], max_length=20)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('salary_from', models.IntegerField()),
                ('salary_to', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_category', to='jobs.category')),
            ],
        ),
    ]
